on:
  push:
    branches:
      - "**"

jobs:
  getGreeting:
    uses: ./.github/workflows/getGreeting.yaml

  logConfig:
    needs: getGreeting
    runs-on: ubuntu-latest
    steps:
      - name: Log Config
        run: |
          greeting=${{ needs.getGreeting.outputs.greeting }}

          if [ -z "$greeting" ]; then
            echo "Not greeting anyone :(";
            exit 1
          else
            echo $greeting;
          fi
